apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kaniko-build
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: DOCKERFILE
        description: Path to the Dockerfile to build.
        default: ./Dockerfile
      - name: CONTEXT
        description: The build context used by Docker.
        default: ./
      - name: BUILDER_IMAGE
        description: The image on which builds will run
        default: silverbulllet/myapp-demo:latest
  steps:
    - name: kaniko-build
      workingDir: /workspace/source
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=$(inputs.params.DOCKERFILE)
        - --destination=$(inputs.params.BUILDER_IMAGE)
        - --context=$(inputs.params.CONTEXT)
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
    - name: docker-library
      hostPath:
        path: /var/lib/docker
