apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: myapp-demo-kaniko
spec:
  params:
    - name: BUILDER_IMAGE
      description: The image on which builds will run
      default: silverbullet/myapp-demo:latest
  resources:
    - name: source
      type: git
  tasks:
    - name: build
      taskRef:
        name: kaniko-build
      params:
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
      resources:
        inputs:
          - name: source
            resource: source
    - name: deploy
      runAfter: [build]
      taskRef:
        name: deploy-kubectl
      resources:
        inputs:
          - name: source
            resource: source
